name: bill_split
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.1
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0+1
  google_sign_in: ^4.5.9
  cloud_firestore: ^0.16.0
  flip_card: ^0.4.4
  gradient_widgets: ^0.5.2
  bottom_navy_bar: ^5.6.0
  convex_bottom_bar: ^2.6.0
  rflutter_alert: ^1.1.0
  mongo_dart: ^0.4.4
  sqflite: ^1.3.2+3
  firebase_database: ^6.0.0
  shared_preferences: ^0.5.12+4
  path_provider: ^1.6.27

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - images/


  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik-Light.ttf
          weight: 200
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 400

